name: "Snyk Notify GH Action"

on:
  pull_request:
  push:
    branches:
      # Update to master branch
      - master

jobs:
  prCheck:
  # Confirm PR Check status
    name: waitforstatuschecks
    runs-on: ubuntu-latest
    outputs: 
      output1: ${{ steps.step1.outputs.status }}

    steps:
      # Checks the status of Snyk PR Checks
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@v1"
        with:
          ignoreActions: "waitforstatuschecks" 
          checkInterval: 13
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: 'Set Failure status'
        id: step1
        if: steps.waitforstatuschecks.outputs.status == 'failure'
        run: echo "status=failure" >> "$GITHUB_OUTPUT"

  prReviewer:
    # Add AppSec Reviewer if PR check failed
    needs: prCheck
    if: needs.prCheck.outputs.output1 == 'failure'
    runs-on: ubuntu-latest

    steps:
    - name: Add Reviewers
      uses: madrapps/add-reviewers@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: ${{ vars.REVIEWERS }}
        re-request-when-approved: true
        re-request-when-changes-requested: true
